
const EMAIL_MOC_DATA = [
    { iconName: 'aa', senderName: 'Mohit Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'ra', senderName: 'Rohit Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'sa', senderName: 'Shubham Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'ra', senderName: 'Ronak Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'sa', senderName: 'Sonak Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'aa', senderName: 'Mohit Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'ra', senderName: 'Rohit Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'sa', senderName: 'Shubham Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'ra', senderName: 'Ronak Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'sa', senderName: 'Sonak Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'aa', senderName: 'Mohit Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'ra', senderName: 'Rohit Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'sa', senderName: 'Shubham Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'ra', senderName: 'Ronak Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'sa', senderName: 'Sonak Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'aa', senderName: 'Mohit Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'ra', senderName: 'Rohit Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'sa', senderName: 'Shubham Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'ra', senderName: 'Ronak Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
    { iconName: 'sa', senderName: 'Sonak Agarwal', subject: 'Unable to add User', content: 'Jello team i am facing big issue here', date: '25 Jul'},
]

export default EMAIL_MOC_DATA