import User1 from '../../MocData/Email/UserImages/user_1.jpg'
import User2 from '../../MocData/Email/UserImages/user_2.jpg'
import User3 from '../../MocData/Email/UserImages/user_3.jpg'
import User4 from '../../MocData/Email/UserImages/user_4.jpg'
import User5 from '../../MocData/Email/UserImages/user_5.jpg'
import User6 from '../../MocData/Email/UserImages/user_1.jpg'

export const EMAIL_MOC_DATA = [
{ id: 11, image: User1, name: 'Harshka Agarwal', ago: 'Now', message: 'whats your current status', notification: '03'},
{ id: 12, image: User2, name: 'Peter Agarwal', ago: '5m', message: 'whats your current status', notification: ''},
{ id: 13, image: User3, name: 'Harry Agarwal', ago: '6m', message: 'whats your current status', notification: ''},
{ id: 14, image: User4, name: 'Ron Agarwal', ago: '1w', message: 'whats your current status', notification: '15'},
{ id: 15, image: User5, name: 'Shakira Agarwal', ago: '2m', message: 'whats your current status', notification: '11'},
{ id: 11, image: User1, name: 'Harshka Agarwal', ago: 'Now', message: 'whats your current status', notification: '03'},
{ id: 12, image: User2, name: 'Peter Agarwal', ago: '5m', message: 'whats your current status', notification: ''},
{ id: 11, image: User1, name: 'Harshka Agarwal', ago: 'Now', message: 'whats your current status', notification: '03'},
{ id: 12, image: User2, name: 'Peter Agarwal', ago: '5m', message: 'whats your current status', notification: ''},
{ id: 13, image: User3, name: 'Harry Agarwal', ago: '6m', message: 'whats your current status', notification: ''},
{ id: 14, image: User4, name: 'Ron Agarwal', ago: '1w', message: 'whats your current status', notification: '15'},
{ id: 15, image: User5, name: 'Shakira Agarwal', ago: '2m', message: 'whats your current status', notification: '11'},
{ id: 11, image: User1, name: 'Harshka Agarwal', ago: 'Now', message: 'whats your current status', notification: '03'},
{ id: 12, image: User2, name: 'Peter Agarwal', ago: '5m', message: 'whats your current status', notification: ''},
{ id: 13, image: User3, name: 'Harry Agarwal', ago: '6m', message: 'whats your current status', notification: ''},
{ id: 14, image: User4, name: 'Ron Agarwal', ago: '1w', message: 'whats your current status', notification: '15'},
{ id: 15, image: User5, name: 'Shakira Agarwal', ago: '2m', message: 'whats your current status', notification: '11'},
{ id: 16, image: User6, name: 'Tayler Swift', ago: 'Now', message: 'whats your current status', notification: ''}
]